services:
  fiber:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-fitbyte-prod 
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
