services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: go-fitbyte-dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
